Smoke test deploy
ministryofjustice/staff-device-dhcp-server pull request #4
Opened 2020-08-25 13:40 UTC by emileswarts

WIP Acceptance testing on container boot

2020-08-25 13:55 UTC, jbevan4 approved these changes

2020-08-25 15:48 UTC, Themitchell requested changes

2020-08-25 15:48 UTC, Themitchell commented on docker-compose.yml
>        KEA_CONFIG_BUCKET_NAME: "staff-device-andy-dhcp-config-bucket"
We can remove this line now given we have removed the aws call in development.

2020-08-25 15:57 UTC, jivdhaliwal commented on docker-compose.yml
> +      LOCAL_DEVELOPMENT: "true"
Could we update the readme and remove the line about the .env file since it's no longer needed

2020-08-26 11:11 UTC, jbevan4 approved these changes

2020-08-26 11:13 UTC, merged