Document HA Failover
ministryofjustice/staff-device-dhcp-server pull request #75
Opened 2021-02-09 16:12 UTC by efuaakum

Added documentation of High-Availability failover

2021-02-09 16:41 UTC, neilkidd requested changes

2021-02-09 16:41 UTC, neilkidd commented on documentation/high-availabilty-testing.md
> +The drop time is set to 3 seconds with the `-d` flag, any request taking more than 3 seconds is considered a failed request.
@efuaakum This section is incorrect. It reflects the perf testing.

2021-02-10 09:53 UTC, efuaakum commented on documentation/high-availabilty-testing.md
> +The drop time is set to 3 seconds with the `-d` flag, any request taking more than 3 seconds is considered a failed request.
Updated section to include actual perfdhcp values used

2021-02-10 15:36 UTC, neilkidd approved these changes

2021-02-10 15:39 UTC, merged